package com.example.android.genericnycguide;


import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ListView;
import android.widget.TextView;

import java.util.ArrayList;

/**
 * A simple {@link Fragment} subclass.
 */
public class SitesFragment extends Fragment {
    final ArrayList<Location> locations = new ArrayList<>();

    public SitesFragment() {
        // Required empty public constructor
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.location_list, container, false);

        locations.add(new Location("Fraunces Tavern","54 Pearl St.","Where it gets its name: Named for Samuel Fraunces, who owned and operated the place as the Queen’s Head Tavern during the 18th century and who was later President Washington’s chief steward. What it was before: Throughout most of the 19th century, the main building was used as a boardinghouse; it was rescued from demolition in the early 1900s and largely reconstructed in 1907. Why it’s notable: In one of the tavern’s rooms, George Washington bade a postwar farewell to his fellow officers; it also served as a meeting place for Revolutionaries before and during the war. What it is now: Part museum and part drinking establishment, Fraunces Tavern has numerous places to sit for a pint and a pot pie. Though little of the original structure remains, the reconstructed corner building celebrates its history through portraits of Washington, early American flags and other mementos. Fast fact: A tavern menu from 1914 shows an order of broiled lamb chops to cost 75 cents, a slice of huckleberry pie 15 cents and a glass of Ruppert’s Knickerbocker beer—a popular quaff of the times—10 cents.","site",R.drawable.output));
        locations.add(new Location("Bowling Green","Whitehall Street and Broadway","Where it gets its name: The park originally had a “bowling green,” or green space where the game “bowls” or “squares” would be played. What it was before: Parade ground, marketplace and supposedly the site where Peter Minuit purchased the land of Manhattan from Native Americans. Why it’s notable: Part of its iron fence, which dates back to 1771 and once served to protect an equestrian statue of King George, remains intact. The statue, on the other hand, was toppled at beginning of the Revolution; find a painting of that rebellious event—and soon a re-creation of the piece itself—at the New-York Historical Society. What it is now: A public park—the oldest in the City—with a fountain at its center. Fast fact: The bronze Charging Bull statue was originally dropped off underneath a downtown Christmas tree Mission Impossible–style, before finding its permanent Bowling Green home.","site",R.drawable.output));
        locations.add(new Location("Wall Street","Wall Street","Where it gets its name: From the wall that was erected here by the Dutch in the mid-1600s to mark the northern boundary of their settlement. Walk along the center of the cobblestone block of Wall Street between: Broad and William Streets to see wooden inlays indicating where posts of the original wall used to stand. What it was: before The area once held a slave market. As the street developed, early buildings included Alexander Hamilton’s home and the City’s first bank. Why it’s notable You: might have heard the moniker before: it’s synonymous with the US, and global, financial industry. What it: is now A narrow street lined by high-rise buildings that once held numerous banking headquarters; in actuality, few still call the place home. Some notable s include no. 40, a 70-story tower with a green pyramidal roof like that of the Woolworth Building, and no. 55, a squat, Greek Revival fortress that originally held the Merchants Exchange. Fast fact During the great Wall Street Crash of 1929, the stock market lost roughly a quarter of its value over just a few days.","site",R.drawable.output));
        locations.add(new Location("Castle Clinton","The Battery","Where it gets its name: From DeWitt Clinton, the early 19th-century mayor of New York City (as well as New York governor and failed Federalist presidential candidate). What it was before: A fort called Southwest Battery, which had successive stints as an immigration holding center, the New York City Aquarium, a restaurant and opera house. Why it’s notable: During the War of 1812, the fort—along with three others in the harbor—was heavily armed to protect against British naval advances. What it is now: The curved, sandstone building down in the Battery is the place to depart for ferries to the Statue of Liberty and Ellis Island; the National Parks Service which operates Castle Clinton, runs brief guided tours of the grounds. Fast fact: Despite its active presence during wartime, no shots were ever fired from, or on, Castle Clinton. ","site",R.drawable.output));
        locations.add(new Location("Schermerhorn Row","Schermerhorn","Where it gets its name: From businessman Peter Schermerhorn, a merchant and shipowner who built the the multiuse houses to facilitate the shipping trade. What it was before: Warehouses, hotels, saloons. Why it’s notable: The 14 red-brick warehouses on Front, Fulton, John and South Streets preserve Georgian-Federal architectural details increasingly rare in the redeveloped neighborhood. What it is now: It was remade as South Street Seaport Museum in the early 1990s, with a museum and spaces for events. Fast fact: Sweet’s Restaurant, at 2 and 4 Fulton, was the oldest seafood spot in the City until it closed in 1992, having been established by Abraham Sweet in 1842.","site",R.drawable.output));
        locations.add(new Location("Federal Hall","26 Wall St.","Where it gets its name: It was on this spot on Wall Street that the original Federal Hall, built in 1700 as a city hall and later serving as the nation’s initial capitol building, stood. What is was before: The same building once served as the US Customs House and US Sub-Treasury Building Why it’s notable: The site—though not this building—is where George Washington was sworn in as the first president of the United States. The current Greek revival temple, lined by Corinthian columns, bears some resemblance to its predecessor. What it is now: A National Parks Service–operated museum with artifacts like the bible Washington swore his oath on and memorabilia from the trial of John Peter Zenger, who dared to criticize the British royal governor of New York. Tours are available on weekdays. Fast fact: The bronze statue of Washington that fronts the building is 12 feet tall; a 2-foot cast of John Quincy Adams Ward’s sculpture can be found at the Met Fifth Avenue.","site",R.drawable.output));
        locations.add(new Location("Trinity Church","75 Broadway","Where it gets its name: It’s a common name for churches the world over. What it was before: Two other Trinity Churches have stood here. One burned down during the Revolutionary War; the other was demolished in 1839 after weathering storm damage. Why it’s notable: The brownstone church was built with a spire whose cross topped out at 281 feet, a towering presence in the skyline in the mid-1800s—and much of the rest of that century. The churchyard cemetery, which predates the current church, holds the graves of Alexander Hamilton, Hamilton’s wife Elizabeth Schuyler, Declaration of Independence signer Francis Lewis and early publisher William Bradford.   What it is now: It remains an active Episcopal parish with daily services, though many come here for afternoon guided tours that point out architectural and historical elements of the church. Fast fact: Thanks to a land grant from Queen Anne in 1705, Trinity Church is one of NYC’s biggest landowners—its holdings were valued a couple of years back at $2 billion.","site",R.drawable.output));
        locations.add(new Location("India House","One Hanover Square","Where it gets its name: To give the social club that took over in 1914 an air of exoticism and to recall colonial trade times. What it was before : The building has been home to Hanover Bank, the New York Cotton Exchange and the Haitian Consulate. Why it’s notable: Its brownstone-like facade, which looks like a classic New York City row house, and its collection of antiques. What it is now: A social club and maritime museum, but also the (basement) home to Harry’s Café & Steak. Fast fact: Willard Straight, who helped found the club, purchased the property and donated much of the Asian art that was once on display, was one of the founders of left-leaning magazine New Republic.","site",R.drawable.output));
        locations.add(new Location("New York Stock Exchange","8 Broad St.","Where it gets its name: The exchange dates back to the so-called Buttonwood Agreement from 1792, when a group of merchants met under a buttonwood tree and consented to deal with just one another and take fixed: commissions in deals; 25 years later an expanded group officially ratified itself as the New York Stock & Exchange Board. Where it was: before 40 Wall Street and 10-12 Broad Street. Why it’s notable More: shares are exchanged here than at any other market in the world. The current location is a columned temple with a classical frieze on its pediment where a central female figure, Integrity, is flanked by representations of industry and production.    What it: is now Still the floor where stocks are traded, but off-limits to public visitation since 9/11. Fast fact There are multiple stock exchanges in Lower Manhattan, including the Mercantile Exchange over in Brookfield Place and Nasdaq at One Liberty Plaza (see below).","site",R.drawable.output));
        locations.add(new Location("Alexander Hamilton US Custom House","1 Bowling Green","Where it gets its name: From its time serving as the processing office for imported goods What it was before: The site was once home to Government House, a 1790 mansion that served as a tavern and customs house but lasted a mere 25 years. Why it’s notable: The Beaux-Arts building comes equipped with 44 columns and a rotunda. Adding to its classical exterior are the Daniel Chester French sculptures (representing the continents of America, Asia, Europe and Africa) and Cass Gilbert design; much of the ornamentation is done with a seafaring theme in mind. Bucking tradition, however, the custom house was built to face Bowling Green and other businesses, rather than ships coming in and out of the harbor. What it is now: It serves as the Smithsonian National Museum of the American Indian, home to nearly a million artifacts covering thousands of years of Native American history. Fast fact: Reginald Marsh’s exuberant murals that adorn the rotunda interior were commissioned as a TRAP–WPA project in 1937.   ","site",R.drawable.output));
        locations.add(new Location("American International Building","70 Pine St.","Where it gets its name: Insurance giant AIG had its home here from 1976 to 2008. What it was before: 60 Wall Tower, Cities Services. Why it’s notable: This was the last skyscraper built in Lower Manhattan between the 1930s and the construction of the World Trade Center in the 1960s and early 1970s. It’s best appreciated from up high, where you can see the spiky, Gothic top, or from inside the lobby, which holds art deco detailing in the marble and elevator doors. It did once have a couple of unusual features as well: double-decker elevators, an observation deck and 15th-floor bridge to 60 Wall Street. One that remains can be seen at one of the building’s entrances—a detailed frieze that is a mini version of the entire building. What it is now: Luxury apartments. Fast fact: If you’ve got $3,358 a month to spare for a studio apartment, this could be your place.","site",R.drawable.output));
        locations.add(new Location("One Liberty Plaza","One Liberty Plaza","Where it gets its name: Liberty Street, which abuts the building, got its freedom-loving name in 1794 after the American Revolution (it was previously called Crown Street). What it was before: Originally known as the US Steel Building, which was constructed on the site of the Second Empire–styled Singer Building. Why it’s notable: One Liberty Plaza’s rectangular, monolithic steel frame calls to mind the style of the Twin Towers, perhaps not surprising as both developments were built around the same time. Interestingly enough, the architecture firm that designed it, Skidmore, Owings & Merrill, is also responsible for the new One World Trade Center (see below). What it is now: Offices, including those of Goldman Sachs and Nasdaq. Fast fact: The adjacent Zuccotti Park, which was created as part of the deal for the building, became the main site of protest for the Occupy Wall Street Movement.","site",R.drawable.output));
        locations.add(new Location("African Burial Ground National Monument","290 Broadway","Date Monument established 2006, burial ground circa late 1600s to 1794 Where it gets its name: The area right by City Hall was used as a burial ground for the City’s African-American population, as blacks were not allowed to be interred in the original settled area of New Amsterdam:. Why it’s notable: The grounds were built over in the 1800s as the City pushed northward. In the 1990s, during construction of a federal building, workers found human remains—which led to the discovery and excavation of more than 400 bodies (they’ve since been reinterred). It has helped shine a light onto African-American heritage in early New York City.  What it is now: The monument for this site can be found at Duane and Elk Streets, next to the visitor center in the Ted Weiss Federal Building, which has displays about the burial ground’s history along with an educational film. Fast fact: Roughly around the time the burial ground's use ceased, free blacks and abolitionists were setting up the African Free School on Cliff Street to provide education for NYC's African-American youth.","site",R.drawable.output));
        locations.add(new Location("New York by Gehry","8 Spruce St.","Where it gets its name: From its architect, Frank Gehry, who is one of the best-known designers of modern spaces. What it was before: A parking lot. Why it’s notable: Besides being one of the City’s tallest residential towers at 76 stories and having a design that suggests a building rippling in the wind, it helped punctuate Lower Manhattan’s post-9/11 comeback. Fast fact At the: base of the building is a New York City public school, PS 397, which has around 600 kids between pre-kindergarten and seventh grade.  285: Fulton St.","site",R.drawable.output));
        locations.add(new Location("One World Trade Center","One World Trade Center","Where it gets its name: The name and inspiration for the original World Trade Center dates back to an exhibit at the 1939 World’s Fair. The new centerpiece of the rebuilt World Trade Center had “Freedom Tower” as: its working title, for obvious reasons. It was renamed when the plan for the site and the building’s design changed. Why it’s notable: Aside from its symbolic associations, this glassy tower marks the latest stage in the refashioning of Lower Manhattan’s skyline. Crowned by an observatory from which you can see a country mile, One World Trade Center is the tallest building in the Western Hemisphere, thanks to a towering spire that elevates its height to 1,776 feet. What it is now: An office building and popular visitor destination. Fast fact: Though much of the attention is on the tower’s height, its lobby also stands out: among the pieces of art livening up the white marbled area is José Parlá’s splashy mural One: Union of the Senses, some 90 feet in length.","site",R.drawable.output));
        // setting up list adapter
        LocationAdapter locationAdapter = new LocationAdapter(getActivity(), locations);

        ListView listView = rootView.findViewById(R.id.list_items_container);

        listView.setAdapter(locationAdapter);

        return rootView;
    }

}
